version: "3.8"
services:

  gateway:
    image: nginx:1.19.8-alpine
    ports:
      - 8888:8888
    networks:
      - backend
    volumes:
      - ./BACKEND/Gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./BACKEND/Gateway/api_gateway.conf:/etc/nginx/api_gateway.conf

  profile-service:
    image: nistagram-profile
    container_name: profile-service
    build:
      context: ./BACKEND/profile-service
      dockerfile: Dockerfile
    restart: always
    environment: 
      HOST : ${HOST}
      DIALECT : ${DIALECT}
      DBPORT : ${DBPORT}
      USER : ${USER}
      NAME : ${NAME_PROFILE}
      PASSWORD : ${PASSWORD}
      PROFILE_SERVICE_DOMAIN: ${PROFILE_SERVICE_DOMAIN}
      PROFILE_SERVICE_PORT: ${PROFILE_SERVICE_PORT}
      AUTH_SERVICE_DOMAIN: ${AUTH_SERVICE_DOMAIN}
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
      PORT: ${PROFILE_SERVICE_PORT}
    depends_on: 
      - postgres
    networks:
      - backend

  auth-service:
    image: nistagram-auth
    container_name: auth-service
    build:
      context: ./BACKEND/auth-service
      dockerfile: Dockerfile
    restart: always
    environment:
      HOST: ${HOST}
      DIALECT: ${DIALECT}
      DBPORT: ${DBPORT}
      USER: ${USER}
      NAME: ${NAME_AUTH}
      PASSWORD: ${PASSWORD}
      AUTH_SERVICE_DOMAIN: ${AUTH_SERVICE_DOMAIN}
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
      PORT: ${AUTH_SERVICE_PORT}
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres
    container_name: postgres
    build: 
      context: ./BACKEND/database
      dockerfile: Dockerfile
    ports: 
      - 5432:5432
    restart: on-failure
    environment: 
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root
    networks: 
      - backend

networks:
  backend:
    name: backend
    driver: bridge
